config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "categories#index"

  resources :categories do
    resources :articles
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @article = Article.new
  end

  def create
    @category = Category.find(params[:category_id])
    @article = @category.articles.build(article_params)
    @article.user = current_user

    if @article.save
      redirect_to category_article_url(@category, @article)
    else
      render "new"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(article_params)
      redirect_to category_article_url(@article.category, @article)
    else
      render "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_url
  end

private
  def article_params
    params.require(:article).permit(:title, :price, :description)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for([@article.category, @article]) do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :price %>:
  <%= f.number_field :price %><br />

  <%= f.label :description %>:
  <%= f.text_field :description %>

  <%= f.submit %>

<% end %>

app/views/articles/edit.html.erb
<h3>Edit this article</h3>

<%= render "form" %>

app/views/articles/new.html.erb
<h3>Create an Article for <%=@category.name%></h3>

<%= render "form" %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>

<ul>
  <li>Price: <%= @article.price %></li>
  <li>Description: <%=@article.description %></li>
  <li>Seller: <%= @article.user.email%></li>
</ul>

<%= link_to "edit this article", edit_category_article_path(@article.category, @article) %>

<%= link_to "delete", category_article_path(@article.category, @article), method: :delete %>

app/views/categories/index.html.erb
<h1>Rails Craigslist</h1>

<ul>
<% @categories.each do |category| %>
  <li><%=link_to category.name, category %></li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h3><%=@category.name%></h3>

<ul>
<% @category.articles.each do |article| %>
  <li><%=link_to article.title, category_article_path(@category, article) %></li>
<% end %>
</ul>

<%= link_to "Create new article", new_category_article_path(@category) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCraigslist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= current_user.email %>
      <%= link_to "logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "register", new_user_registration_path %>
      <%= link_to "login", new_user_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>